# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build dnazart

on:
  push:
    branch: master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
    steps:
    - name: Checkout code and Build
      uses: actions/checkout@v2
      with:
        lfs: false
    - name: Setup golang
      uses: actions/setup-go@v2
        with:
          go-version: '1.16'
    - run: ./scripts/package.sh Linux   linux   amd64
    - run: ./scripts/package.sh Mac     darwin  amd64
    - run: ./scripts/package.sh Windows windows amd64
    - name: Upload Release Assets
      # https://github.com/softprops/action-gh-release
      uses: softprops/action-gh-release@v0.1.12
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: false
        draft: true
        files: |
          ./packages/dnazart-v*.zip
          ./packages/dnazart-v*.tar.gz
